matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      services: docker
      before_install:
        - docker pull swift:latest
      script:
        - docker run -v "$(pwd):/src" swift:latest /bin/bash /src/Tests/script.sh
    - os: osx
      osx_image: xcode8.2
      script:
        - /bin/bash Tests/script.sh
